packages:
  - example/
  - packages/*

autoInstallPeers: false

catalogs:
  dev:
    "@eslint/compat": ^1.4.0
    "@eslint/js": ^9.38.0
    "@sveltejs/adapter-static": ^3.0.10
    "@sveltejs/kit": ^2.48.0
    "@sveltejs/vite-plugin-svelte": ^6.2.1
    "@tailwindcss/vite": ^4.1.16
    eslint: ^9.38.0
    eslint-plugin-svelte: ^3.12.5
    globals: ^16.4.0
    jiti: ^2.6.1
    prettier: ^3.6.2
    prettier-plugin-svelte: ^3.4.0
    prettier-plugin-tailwindcss: ^0.7.1
    svelte: ^5.42.2
    svelte-check: ^4.3.3
    tailwindcss: ^4.1.16
    typescript: ^5.9.3
    typescript-eslint: ^8.46.2
    vite: ^7.1.12
    vite-plugin-devtools-json: ^1.0.0
    wxt: ^0.20.11
  peer:
    vite: ^7.1.0
    wxt: ^0.20.11
  types:
    "@types/node": ^24.9.1

engineStrict: true

ignoredBuiltDependencies:
  - esbuild
  - "@tailwindcss/oxide"
  - spawn-sync

patchedDependencies:
  "@sveltejs/kit": patches/@sveltejs__kit.patch

strictDepBuilds: true

strictPeerDependencies: true
